# Generated by Django 4.0.4 on 2022-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('date_published', models.DateField()),
                ('translator', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name', 'date_published'],
            },
        ),
    ]
